server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://35.212.254.58:3306/taekItEasy
    username: root
    password: takeiteasy
    driver-class-name: com.mysql.cj.jdbc.Driver

  openai.model: text-davinci-001
  openai.secret-key : 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